<?php
/**
 * CatalogDataCategoryInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * CatalogDataCategoryInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class CatalogDataCategoryInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CatalogDataCategoryInterface"
     */
    public function testCatalogDataCategoryInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "parentId"
     */
    public function testPropertyParentId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {

    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {

    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {

    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {

    }

    /**
     * Test attribute "availableSortBy"
     */
    public function testPropertyAvailableSortBy()
    {

    }

    /**
     * Test attribute "includeInMenu"
     */
    public function testPropertyIncludeInMenu()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "customAttributes"
     */
    public function testPropertyCustomAttributes()
    {

    }

}
