<?php
/**
 * DownloadableDataLinkInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * DownloadableDataLinkInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class DownloadableDataLinkInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DownloadableDataLinkInterface"
     */
    public function testDownloadableDataLinkInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "sortOrder"
     */
    public function testPropertySortOrder()
    {

    }

    /**
     * Test attribute "isShareable"
     */
    public function testPropertyIsShareable()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "numberOfDownloads"
     */
    public function testPropertyNumberOfDownloads()
    {

    }

    /**
     * Test attribute "linkType"
     */
    public function testPropertyLinkType()
    {

    }

    /**
     * Test attribute "linkFile"
     */
    public function testPropertyLinkFile()
    {

    }

    /**
     * Test attribute "linkFileContent"
     */
    public function testPropertyLinkFileContent()
    {

    }

    /**
     * Test attribute "linkUrl"
     */
    public function testPropertyLinkUrl()
    {

    }

    /**
     * Test attribute "sampleType"
     */
    public function testPropertySampleType()
    {

    }

    /**
     * Test attribute "sampleFile"
     */
    public function testPropertySampleFile()
    {

    }

    /**
     * Test attribute "sampleFileContent"
     */
    public function testPropertySampleFileContent()
    {

    }

    /**
     * Test attribute "sampleUrl"
     */
    public function testPropertySampleUrl()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
