<?php
/**
 * GiftWrappingDataWrappingInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * GiftWrappingDataWrappingInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface WrappingInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class GiftWrappingDataWrappingInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GiftWrappingDataWrappingInterface"
     */
    public function testGiftWrappingDataWrappingInterface()
    {

    }

    /**
     * Test attribute "wrappingId"
     */
    public function testPropertyWrappingId()
    {

    }

    /**
     * Test attribute "design"
     */
    public function testPropertyDesign()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "basePrice"
     */
    public function testPropertyBasePrice()
    {

    }

    /**
     * Test attribute "imageName"
     */
    public function testPropertyImageName()
    {

    }

    /**
     * Test attribute "imageBase64Content"
     */
    public function testPropertyImageBase64Content()
    {

    }

    /**
     * Test attribute "baseCurrencyCode"
     */
    public function testPropertyBaseCurrencyCode()
    {

    }

    /**
     * Test attribute "websiteIds"
     */
    public function testPropertyWebsiteIds()
    {

    }

    /**
     * Test attribute "imageUrl"
     */
    public function testPropertyImageUrl()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
