<?php
/**
 * GiftCardAccountDataGiftCardAccountInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * GiftCardAccountDataGiftCardAccountInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Gift Card Account data
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class GiftCardAccountDataGiftCardAccountInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GiftCardAccountDataGiftCardAccountInterface"
     */
    public function testGiftCardAccountDataGiftCardAccountInterface()
    {

    }

    /**
     * Test attribute "giftCards"
     */
    public function testPropertyGiftCards()
    {

    }

    /**
     * Test attribute "giftCardsAmount"
     */
    public function testPropertyGiftCardsAmount()
    {

    }

    /**
     * Test attribute "baseGiftCardsAmount"
     */
    public function testPropertyBaseGiftCardsAmount()
    {

    }

    /**
     * Test attribute "giftCardsAmountUsed"
     */
    public function testPropertyGiftCardsAmountUsed()
    {

    }

    /**
     * Test attribute "baseGiftCardsAmountUsed"
     */
    public function testPropertyBaseGiftCardsAmountUsed()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
