<?php
/**
 * GiftCardDataGiftCardOptionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * GiftCardDataGiftCardOptionInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface GiftCardOptionInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class GiftCardDataGiftCardOptionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GiftCardDataGiftCardOptionInterface"
     */
    public function testGiftCardDataGiftCardOptionInterface()
    {

    }

    /**
     * Test attribute "giftcardAmount"
     */
    public function testPropertyGiftcardAmount()
    {

    }

    /**
     * Test attribute "customGiftcardAmount"
     */
    public function testPropertyCustomGiftcardAmount()
    {

    }

    /**
     * Test attribute "giftcardSenderName"
     */
    public function testPropertyGiftcardSenderName()
    {

    }

    /**
     * Test attribute "giftcardRecipientName"
     */
    public function testPropertyGiftcardRecipientName()
    {

    }

    /**
     * Test attribute "giftcardSenderEmail"
     */
    public function testPropertyGiftcardSenderEmail()
    {

    }

    /**
     * Test attribute "giftcardRecipientEmail"
     */
    public function testPropertyGiftcardRecipientEmail()
    {

    }

    /**
     * Test attribute "giftcardMessage"
     */
    public function testPropertyGiftcardMessage()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
