<?php
/**
 * QuoteDataShippingMethodInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * QuoteDataShippingMethodInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface ShippingMethodInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class QuoteDataShippingMethodInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataShippingMethodInterface"
     */
    public function testQuoteDataShippingMethodInterface()
    {

    }

    /**
     * Test attribute "carrierCode"
     */
    public function testPropertyCarrierCode()
    {

    }

    /**
     * Test attribute "methodCode"
     */
    public function testPropertyMethodCode()
    {

    }

    /**
     * Test attribute "carrierTitle"
     */
    public function testPropertyCarrierTitle()
    {

    }

    /**
     * Test attribute "methodTitle"
     */
    public function testPropertyMethodTitle()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "baseAmount"
     */
    public function testPropertyBaseAmount()
    {

    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "errorMessage"
     */
    public function testPropertyErrorMessage()
    {

    }

    /**
     * Test attribute "priceExclTax"
     */
    public function testPropertyPriceExclTax()
    {

    }

    /**
     * Test attribute "priceInclTax"
     */
    public function testPropertyPriceInclTax()
    {

    }

}
