<?php
/**
 * QuoteDataCartInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * QuoteDataCartInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface CartInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class QuoteDataCartInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataCartInterface"
     */
    public function testQuoteDataCartInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "convertedAt"
     */
    public function testPropertyConvertedAt()
    {

    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "isVirtual"
     */
    public function testPropertyIsVirtual()
    {

    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {

    }

    /**
     * Test attribute "itemsCount"
     */
    public function testPropertyItemsCount()
    {

    }

    /**
     * Test attribute "itemsQty"
     */
    public function testPropertyItemsQty()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {

    }

    /**
     * Test attribute "reservedOrderId"
     */
    public function testPropertyReservedOrderId()
    {

    }

    /**
     * Test attribute "origOrderId"
     */
    public function testPropertyOrigOrderId()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "customerIsGuest"
     */
    public function testPropertyCustomerIsGuest()
    {

    }

    /**
     * Test attribute "customerNote"
     */
    public function testPropertyCustomerNote()
    {

    }

    /**
     * Test attribute "customerNoteNotify"
     */
    public function testPropertyCustomerNoteNotify()
    {

    }

    /**
     * Test attribute "customerTaxClassId"
     */
    public function testPropertyCustomerTaxClassId()
    {

    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
