<?php
/**
 * QuoteDataCurrencyInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * QuoteDataCurrencyInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface CurrencyInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class QuoteDataCurrencyInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataCurrencyInterface"
     */
    public function testQuoteDataCurrencyInterface()
    {

    }

    /**
     * Test attribute "globalCurrencyCode"
     */
    public function testPropertyGlobalCurrencyCode()
    {

    }

    /**
     * Test attribute "baseCurrencyCode"
     */
    public function testPropertyBaseCurrencyCode()
    {

    }

    /**
     * Test attribute "storeCurrencyCode"
     */
    public function testPropertyStoreCurrencyCode()
    {

    }

    /**
     * Test attribute "quoteCurrencyCode"
     */
    public function testPropertyQuoteCurrencyCode()
    {

    }

    /**
     * Test attribute "storeToBaseRate"
     */
    public function testPropertyStoreToBaseRate()
    {

    }

    /**
     * Test attribute "storeToQuoteRate"
     */
    public function testPropertyStoreToQuoteRate()
    {

    }

    /**
     * Test attribute "baseToGlobalRate"
     */
    public function testPropertyBaseToGlobalRate()
    {

    }

    /**
     * Test attribute "baseToQuoteRate"
     */
    public function testPropertyBaseToQuoteRate()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
