<?php
/**
 * QuoteDataTotalsInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * QuoteDataTotalsInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface TotalsInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class QuoteDataTotalsInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataTotalsInterface"
     */
    public function testQuoteDataTotalsInterface()
    {

    }

    /**
     * Test attribute "grandTotal"
     */
    public function testPropertyGrandTotal()
    {

    }

    /**
     * Test attribute "baseGrandTotal"
     */
    public function testPropertyBaseGrandTotal()
    {

    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {

    }

    /**
     * Test attribute "baseSubtotal"
     */
    public function testPropertyBaseSubtotal()
    {

    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {

    }

    /**
     * Test attribute "baseDiscountAmount"
     */
    public function testPropertyBaseDiscountAmount()
    {

    }

    /**
     * Test attribute "subtotalWithDiscount"
     */
    public function testPropertySubtotalWithDiscount()
    {

    }

    /**
     * Test attribute "baseSubtotalWithDiscount"
     */
    public function testPropertyBaseSubtotalWithDiscount()
    {

    }

    /**
     * Test attribute "shippingAmount"
     */
    public function testPropertyShippingAmount()
    {

    }

    /**
     * Test attribute "baseShippingAmount"
     */
    public function testPropertyBaseShippingAmount()
    {

    }

    /**
     * Test attribute "shippingDiscountAmount"
     */
    public function testPropertyShippingDiscountAmount()
    {

    }

    /**
     * Test attribute "baseShippingDiscountAmount"
     */
    public function testPropertyBaseShippingDiscountAmount()
    {

    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "baseTaxAmount"
     */
    public function testPropertyBaseTaxAmount()
    {

    }

    /**
     * Test attribute "weeeTaxAppliedAmount"
     */
    public function testPropertyWeeeTaxAppliedAmount()
    {

    }

    /**
     * Test attribute "shippingTaxAmount"
     */
    public function testPropertyShippingTaxAmount()
    {

    }

    /**
     * Test attribute "baseShippingTaxAmount"
     */
    public function testPropertyBaseShippingTaxAmount()
    {

    }

    /**
     * Test attribute "subtotalInclTax"
     */
    public function testPropertySubtotalInclTax()
    {

    }

    /**
     * Test attribute "baseSubtotalInclTax"
     */
    public function testPropertyBaseSubtotalInclTax()
    {

    }

    /**
     * Test attribute "shippingInclTax"
     */
    public function testPropertyShippingInclTax()
    {

    }

    /**
     * Test attribute "baseShippingInclTax"
     */
    public function testPropertyBaseShippingInclTax()
    {

    }

    /**
     * Test attribute "baseCurrencyCode"
     */
    public function testPropertyBaseCurrencyCode()
    {

    }

    /**
     * Test attribute "quoteCurrencyCode"
     */
    public function testPropertyQuoteCurrencyCode()
    {

    }

    /**
     * Test attribute "couponCode"
     */
    public function testPropertyCouponCode()
    {

    }

    /**
     * Test attribute "itemsQty"
     */
    public function testPropertyItemsQty()
    {

    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {

    }

    /**
     * Test attribute "totalSegments"
     */
    public function testPropertyTotalSegments()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
