<?php
/**
 * SalesRuleDataCouponGenerationSpecInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * SalesRuleDataCouponGenerationSpecInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description CouponGenerationSpecInterface
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class SalesRuleDataCouponGenerationSpecInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SalesRuleDataCouponGenerationSpecInterface"
     */
    public function testSalesRuleDataCouponGenerationSpecInterface()
    {

    }

    /**
     * Test attribute "ruleId"
     */
    public function testPropertyRuleId()
    {

    }

    /**
     * Test attribute "format"
     */
    public function testPropertyFormat()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {

    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {

    }

    /**
     * Test attribute "suffix"
     */
    public function testPropertySuffix()
    {

    }

    /**
     * Test attribute "delimiterAtEvery"
     */
    public function testPropertyDelimiterAtEvery()
    {

    }

    /**
     * Test attribute "delimiter"
     */
    public function testPropertyDelimiter()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
