<?php
/**
 * TaxDataTaxRateInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * TaxDataTaxRateInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Tax rate interface.
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class TaxDataTaxRateInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TaxDataTaxRateInterface"
     */
    public function testTaxDataTaxRateInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "taxCountryId"
     */
    public function testPropertyTaxCountryId()
    {

    }

    /**
     * Test attribute "taxRegionId"
     */
    public function testPropertyTaxRegionId()
    {

    }

    /**
     * Test attribute "regionName"
     */
    public function testPropertyRegionName()
    {

    }

    /**
     * Test attribute "taxPostcode"
     */
    public function testPropertyTaxPostcode()
    {

    }

    /**
     * Test attribute "zipIsRange"
     */
    public function testPropertyZipIsRange()
    {

    }

    /**
     * Test attribute "zipFrom"
     */
    public function testPropertyZipFrom()
    {

    }

    /**
     * Test attribute "zipTo"
     */
    public function testPropertyZipTo()
    {

    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {

    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {

    }

    /**
     * Test attribute "titles"
     */
    public function testPropertyTitles()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
