<?php
/**
 * VaultDataPaymentTokenInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the model.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

/**
 * VaultDataPaymentTokenInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Gateway vault payment token interface.
/**
 * @package     TheCodeBunny\Swagger\Magento2\Client
 * @author      Hemang Vyas (TheCodeBunny)
 * @link        https://github.com/thecodebunny/TcbMagento2Api.git
 */
class VaultDataPaymentTokenInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "VaultDataPaymentTokenInterface"
     */
    public function testVaultDataPaymentTokenInterface()
    {

    }

    /**
     * Test attribute "entityId"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "customerId"
     */
    public function testPropertyCustomerId()
    {

    }

    /**
     * Test attribute "publicHash"
     */
    public function testPropertyPublicHash()
    {

    }

    /**
     * Test attribute "paymentMethodCode"
     */
    public function testPropertyPaymentMethodCode()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "expiresAt"
     */
    public function testPropertyExpiresAt()
    {

    }

    /**
     * Test attribute "gatewayToken"
     */
    public function testPropertyGatewayToken()
    {

    }

    /**
     * Test attribute "tokenDetails"
     */
    public function testPropertyTokenDetails()
    {

    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "isVisible"
     */
    public function testPropertyIsVisible()
    {

    }

}
