<?php
/**
 * CustomerGroupRepositoryV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the endpoint.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

use \TheCodeBunny\Magento2Api\Configuration;
use \TheCodeBunny\Magento2Api\ApiClient;
use \TheCodeBunny\Magento2Api\ApiException;
use \TheCodeBunny\Magento2Api\ObjectSerializer;

/**
 * CustomerGroupRepositoryV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */
class CustomerGroupRepositoryV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for customerGroupRepositoryV1DeleteByIdDelete
     *
     * .
     *
     */
    public function testCustomerGroupRepositoryV1DeleteByIdDelete()
    {

    }

    /**
     * Test case for customerGroupRepositoryV1GetByIdGet
     *
     * .
     *
     */
    public function testCustomerGroupRepositoryV1GetByIdGet()
    {

    }

    /**
     * Test case for customerGroupRepositoryV1GetListGet
     *
     * .
     *
     */
    public function testCustomerGroupRepositoryV1GetListGet()
    {

    }

    /**
     * Test case for customerGroupRepositoryV1SavePost
     *
     * .
     *
     */
    public function testCustomerGroupRepositoryV1SavePost()
    {

    }

    /**
     * Test case for customerGroupRepositoryV1SavePut
     *
     * .
     *
     */
    public function testCustomerGroupRepositoryV1SavePut()
    {

    }

}
