<?php
/**
 * QuoteCouponManagementV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/thecodebunny/TcbMagento2Api.git)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/thecodebunny/TcbMagento2Api.git.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/thecodebunny/TcbMagento2Api.git
 * Please update the test case below to test the endpoint.
 */

namespace TheCodeBunny\Swagger\Magento2\Client;

use \TheCodeBunny\Magento2Api\Configuration;
use \TheCodeBunny\Magento2Api\ApiClient;
use \TheCodeBunny\Magento2Api\ApiException;
use \TheCodeBunny\Magento2Api\ObjectSerializer;

/**
 * QuoteCouponManagementV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheCodeBunny\Swagger\Magento2\Client
 * @author   Hemang Vyas (TheCodeBunny)
 * @link     https://github.com/thecodebunny/TcbMagento2Api.git
 */
class QuoteCouponManagementV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for quoteCouponManagementV1GetGet
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1GetGet()
    {

    }

    /**
     * Test case for quoteCouponManagementV1GetGet_0
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1GetGet0()
    {

    }

    /**
     * Test case for quoteCouponManagementV1RemoveDelete
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1RemoveDelete()
    {

    }

    /**
     * Test case for quoteCouponManagementV1RemoveDelete_0
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1RemoveDelete0()
    {

    }

    /**
     * Test case for quoteCouponManagementV1SetPut
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1SetPut()
    {

    }

    /**
     * Test case for quoteCouponManagementV1SetPut_0
     *
     * .
     *
     */
    public function testQuoteCouponManagementV1SetPut0()
    {

    }

}
